apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/name: app-a
      name: service-a
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
      selector:
        app.kubernetes.io/name: app-a
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/name: app-b
      name: service-b
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
      selector:
        app.kubernetes.io/name: app-b
      type: ClusterIP
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/name: app-a
      name: deployment-a
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: app-a
      template:
        metadata:
          labels:
            app.kubernetes.io/name: app-a
        spec:
          containers:
            - name: app-a
              image: app-a
              imagePullPolicy: Never
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  cpu: 300m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/name: app-b
      name: deployment-b
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: app-b
      template:
        metadata:
          labels:
            app.kubernetes.io/name: app-b
        spec:
          containers:
            - name: app-b
              image: app-b
              imagePullPolicy: Never
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  cpu: 300m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001